//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeakAndPlatePredictor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeakAndPlateManager
    {
        public int IdPeakAndPlateManager { get; set; }
        public int LastPlateDigit { get; set; }
        public int IdRestrictionRules { get; set; }
    
        public virtual RestrictionRule RestrictionRule { get; set; }
    }
}
