//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeakAndPlatePredictor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestrictionRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestrictionRule()
        {
            this.PeakAndPlateManagers = new HashSet<PeakAndPlateManager>();
        }
    
        public int IdRestrictionRules { get; set; }
        public int IdTimeInterval { get; set; }
        public int IdDateRules { get; set; }
    
        public virtual DateRule DateRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeakAndPlateManager> PeakAndPlateManagers { get; set; }
        public virtual TimeInterval TimeInterval { get; set; }
    }
}
